### ISSUE TITLE
Use lightstreamer for access other rtd

### ISSUE THREAD

**Issue by lucked** [Lightstreamer/Lightstreamer-example-StockList-client-javascript#2]
can i use lightstreamer js client for access a stock rtd server?

**Comment by Bravo27** [comment]
Your scenario is not entirely clear to me. However, if you want to use a rtd server as a data feed you should integrate the acquisition of rtd updates into a Data Adapter, maybe with the .NET Adapter API, and inject them into the Lightstreamer server.
Then at the client side you can use the js library, or any other, at your convenience.
